on: push
name: deploy
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to DockerHub
      uses: docker/login-action@v1
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: buid
      run: docker build -t runclexpress .
    - name: Tags
      run: |
        docker tag back ${{ secrets.DOCKER_USERNAME }}/back:${{ github.sha }}
        docker tag back ${{ secrets.DOCKER_USERNAME }}/back:latest
    - name: Push
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/back:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/back:latest
